frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Button/index.ts, frontend/src/components/Button/index.tsx, frontend/src/components/TextField/index.ts, frontend/src/components/TextField/index.tsx, frontend/src/components/layout/Menu/Menu.tsx, frontend/src/components/layout/Menu/MenuContainer.tsx, frontend/src/components/layout/Menu/index.ts, frontend/src/components/layout/Menu/styled.ts, frontend/src/components/layout/styled.ts, frontend/src/constants/menuRoles.tsx, frontend/src/constants/routes.ts, frontend/src/pages/Employees/Employees.tsx, frontend/src/pages/Employees/index.ts, frontend/src/pages/Requests/Requests.tsx, frontend/src/pages/Requests/index.ts, frontend/src/pages/Skills/Skills.tsx, frontend/src/pages/Skills/index.ts, frontend/src/pages/index.ts, frontend/tsconfig.json
**Overview:**
1. Implement Menu according to Role of the client 
Now we can change the role manually in this way:
`export const menuItems = ROLES_MENU['employee'];` 
('employee', 'manager', and 'admin' roles are available for use)
Later we will get user's role from the server
2. Add Employees, Requests and Skills pages
3. Change index.ts in components folders for better readability 
4. Add MenuContainer and styled.js inside Menu folder
=> feat: implement menu according to the role (V1-015)

frontend/src/components/Layout/Menu/styled.ts
We had a problem with menu width, so it seemed like pages content was not centered, even though it was. I've set visible menu width to equal real width of its container (grid element).
=> Fixed: No Content displayed in center

frontend/src/pages/NotFound/NotFound.tsx, frontend/src/pages/NotFound/NotFoundContainer.tsx, frontend/src/pages/NotFound/index.ts, frontend/src/pages/NotFound/styled.ts
Overview:
1. Implement 2 types of displaying the Not Found page : for authorised and unauthorised users
If the user is not logged in and tries to open a page with an incorrect URL, the top bar and menu are not displayed, only the error is displayed
=> V1-050 feat: implement correct Not Found page displaying for unauthorised users

backend/src/controllers/tests/startTest.ts, backend/src/utils/validation/checkDuplicates.ts
>  
> New rules to start the testing:
> - status: `started`
> - course progress: `100%`
=> Bugfix/v1-090. Fixed rules of startTest endpoint according to QA issues.

frontend/src/api/courses/getCourseInfo.ts, frontend/src/api/myCourses/finishClientCourse.ts, frontend/src/api/myCourses/getMyCourseInfo.ts, frontend/src/api/myCourses/index.ts, frontend/src/api/myCourses/passClientCourse.ts, frontend/src/api/myCourses/startClientCourse.ts, frontend/src/components/Button/Button.tsx, frontend/src/constants/test.ts, frontend/src/pages/CoursesList/CoursesList.tsx, frontend/src/pages/CoursesList/styled.ts, frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx, frontend/src/pages/LearningCourse/LearningCourse.tsx, frontend/src/pages/LearningCourse/LearningCourseContainer.tsx, frontend/src/pages/PassingTest/PassingTestContainer.tsx, frontend/src/pages/PassingTest/TestResult/TestResult.tsx, frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx, frontend/src/themeSettings.ts, frontend/src/types/test.ts
**Overview:**
> 1. Implemented startClientCourse API request, so now course status changes from 'approved' to 'started'
> 2. Implemented finishClientCourse API request, so now course status changes from 'testing' to 'completed' in case of successful test passing on 'Submit' button click
> 3. Implemented passClientCourse API request, so now an error '"Can not start test till course stages haven't been passed." is fixed
> 4. Fixed an error causing that the percentage of test completion didn't count
> 5. Added "Completed" button instead of a "Start the course" button on the Courses list page's card if the course is completed (V1-096)
=> Bugfix/V1-073 + V1-096 + API requests for learning course

frontend/src/components/Course/styled.ts, frontend/src/components/ProgressBar/ProgressBar.tsx, frontend/src/constants/detailedCourse.tsx, frontend/src/constants/progressBar.ts, frontend/src/constants/statuses.ts, frontend/src/pages/DetailedCourse/DetailedCourse.tsx, frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx, frontend/src/pages/DetailedCourse/styled.ts, frontend/src/pages/MyCourses/styled.ts, frontend/src/types/detailedCourse.ts, frontend/src/types/progressBar.ts
**Overview:** 
1. If the user has completed the test, on the "Details" page the text in the percentage completion area changed to "Completed" and the button changed  to "Completed" and disabled instead of "Start the course"
2. The name of the button on the Details page changed to the same as on the "My courses" page
3. Added a "successful" progress bar variant to use on the "Details" page in case of successful course completion.
4. Moved Detailed course and ProgressBar interfaces to the types folder
5. Removed Detailed course mocked data from constants
=> V1-120 & V1-114 Bugfix "Details" page

frontend/src/pages/DetailedCourse/DetailedCourse.tsx
**Overview:**
When the user clicks on the Details button on the Courses list (not client courses), two buttons were displayed on the Details page, it was fixed and now only one button is displaying
=> V1-120 fixed button displaying on the Details page

frontend/src/api/test/sendTestResult.ts
Fixed a bug which if the user successfully passed the test, the acquired skills were displayed on the profile page only after reload but not immediately
=> bug/v1-134 | Fixed issue when passed test displayed only after reloading profile page

frontend/src/pages/PassingTest/QuestionItem/styled.ts
Fixed an issue:
1. On screens with a width of 1440 pixels, 1920 pixels or more, the answers to the questions should not be torn and move to the next line if the length of the screen allows you to display the answer in one line
=> V1-101 Bugfix: fixed responsive test answer length

frontend/src/constants/menuRoles.tsx
There was an implemented menu for admin already i just removed 'help' tab as it shown in design
=> V1/146 | Fixed menu for admin role

frontend/src/utils/helpers/videoPlayer/videoLink.ts
>
> Despite the fact, that we thought the problem was in video duration, it actually was in links optimization.
>
> Changed `optimizeLink` helper logics. Now optimization is not performed when it is not necessary.
>
> Run your local apps on this PR's branch (backend with `dev` mode), authorize as `user` and go to "QA for everyone" course in `MyCourses` page. I've added new temporal stage with long-duration video there. It seems to work now.
> P.S.
> It was the shortest bugfix I have ever had on this project, but I've spent several hours on it.
=> Feature/v1-145 | Fixed bug with videos not played.

frontend/src/components/Avatar/styled.ts, frontend/src/pages/Requests/RequestItem/styled.ts, frontend/src/pages/Requests/Requests.tsx, frontend/src/pages/Requests/styled.ts
**Overview:**
Fixed the next issues:
1. On devices with a resolution of 1441px or more, the user's avatar is large
2. The size of the course image should be 30x20
3. The font size of the buttons "Apply", "Accept with interview", "Reject" should be 16px
4. The size of the "Accept" and "Reject" buttons should be 64x34px, the size of the "Accept with interview" button should be 165x34px
5. The "No requests" text should be displayed in the middle of the screen (should have the same styles as "No courses yet" on the My courses page)
=>  Bugfix/v1-129 Requests page styles 

frontend/src/pages/PassingTest/PassingTestContainer.tsx
When the user failed the test in the allotted time, a modal window is displayed
when the user closes this window (via "OK" button or cross icon), he is redirected to the course page with result
=> bug/v1-170 | Fixed redirect if test time is over

frontend/src/components/Button/HOC/withDisable.tsx, frontend/src/constants/statuses.ts
Fixed: When user failed the test, then the "Failed" button is displayed on the My Courses page and on the Details page.
Result: "Continue' button displayed on the My Course page and on the Details page
=> bug/V1-182 | Changed the label btn to 'Continue' if user failed the test

backend/src/controllers/clientCourses/finishCourse.ts
Now api responses on finish course with `OK` only when status is `successful`.
=> Bugfix/v1-127 | Invalid response bug fixed

frontend/src/App.tsx
1. Not found page was opened instead of Employees and EmployeeProfile pages. The 500 error displayed
=> V1-076 Bugfix: fixed app routes for correct pages displaying

backend/src/controllers/admin/editCourse.ts, backend/src/db/models/Course.ts, backend/src/interfaces/ICourses/IQueryCourses.ts, backend/src/interfaces/Ientities/Icourses.ts, backend/src/utils/validation/isValidAvatar.ts, backend/src/utils/validation/isValidTitle.ts
Added new functionality to endpoint `[PUT] /api/courses/:id/edit` :
1. Now you can additionally pass title or avatar fields to update existing course. Example:
```
{
"avatar": "https://imageio.forbes.com/specials-images/imageserve/5faad4255239c9448d6c7bcd/Best-Animal-Photos-Contest--Close-Up-Of-baby-monkey/960x0.jpg?fit=bounds&format=jpg&width=960",
"title": "DAPO TESTS PURPOSE",
"description": "UPDATED TWICE",
...
}
```
2. Also some minor models and interfaces changes.
=> Improve/v1-161 | Added ability to update course title and avatar.

frontend/src/components/ProgressBar/ProgressBar.tsx, frontend/src/constants/progressBar.ts, frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/EmployeeCoursesList.tsx, frontend/src/utils/helpers/convertCourseStatusToProgress.ts
**Overview:**
> 1. Added convertEmployeeCourseProgress helper, cause on Employee page the styles are different
> 2. Added ProgressBar variants: employeeNotStarted and employeeFailed
> 3. Moved default TRAIL_COLOR to constants
> 4. Fixed ProgressBar styles on Employee courses page according to QA review
=> V1-076 ProgressBar styles on Employee profile courses 

frontend/src/pages/SignIn/SignInForm/styled.ts
> Login and password fields are glued together on the devices where resolution from 425px to 1280px
=> V1-203 Bugfix: fixed SignIn form styles on responsive design

frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/CourseItem/styled.ts
Fixed bug where long name went outside the bounds of the component
=> bug/v1-195 | Fixed width for course title in Employee profile page

backend/migrations-backdev/20220411135726-added-types-for-materials.js, backend/migrations/20220411150120-added-types-for-materials.js
- added missed content `type` and `material` fields to Ruby course material element.
- replaced Salesforce course material type with `plain` instead of `video`.
=> Bug/v1-210 | Fixed migrations issues.

frontend/src/components/TextTooltip/TextTooltip.tsx, frontend/src/components/TextTooltip/index.ts, frontend/src/components/TextTooltip/styled.ts, frontend/src/components/TextTooltip/types.ts, frontend/src/enums/employee.ts, frontend/src/pages/Employees/EmployeesList/EmployeeContent/EmployeeContent.tsx
- Frontend
1. Fixed content overflow for phone and skype column at Employee page
2. Added reusable component TextTooltip
=> Bugfix | V1-206 - Fixed content overflow for phone and skype column at Employee page

frontend/src/pages/PendingAssessments/PendingAssessments.tsx, frontend/src/pages/PendingAssessments/PendingAssessmentsContainer.tsx, frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtons.tsx, frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtonsContainer.tsx, frontend/src/pages/PendingAssessments/types.ts
1. Now loaders displaying only in buttons related to particular request.
2. Message `NO REQUESTS` displayed if no pending assessments found.
=> Bugfix/v1-199 | Fixed no requests message and buttons loaders.

backend/src/controllers/admin/getTest.ts, backend/src/db/providers/testProvider.ts, backend/src/enums/routesEnum.ts, backend/src/interfaces/requests/tests/getTest.d.ts, backend/src/routing/routes.ts, backend/src/routing/testsRouter.ts
New endpoint `[GET] /api/tests/:id` for ADMIN role only. Responses with test data. `:id` is test's `_id`.
=> Feature/V1-250 | Implemented get test admin API.

frontend/src/pages/Skills/SkillGroup/SkillGroup.tsx, frontend/src/pages/Skills/SkillGroup/styled.ts, frontend/src/pages/Skills/Skills.tsx, frontend/src/pages/Skills/styled.ts, frontend/src/pages/Skills/utils.ts
1. Checked:  The skill name should be displayed max in two lines (work correct with utils using)
2. Fixed:  the text "No skills" should be displayed in the center of the page
=> bug/Fixed Skill components for admin

backend/src/utils/schedule/updateTestStatuses.ts
1. Fixed test-ban scheduler: updating courses with statuses: `testing`, `failed`
2. Fixed test-ban scheduler: diapason changed to avoid loosing db integrity if server is down
=> Bugfix/V1-260 | Fixed scheduler time diapasons and status checks.

frontend/src/constants/courseEditor.ts, frontend/src/pages/CourseEditor/LessonsStep/LessonItem/LessonItem.tsx, frontend/src/pages/CourseEditor/LessonsStep/LessonItem/styled.ts, frontend/src/validations/schemas/courseEditorValidationSchema.ts
The error next to the Exercise description field is displayed when the admin starts typing in the Exercise title field. There should be a hint under the Exercise Description field "Exercise should contain both title and description" in color #A2A2A2
=> V1-269 Bugfix: changed exercise errors displaying
