- frontend/.husky/pre-commit
- frontend/package.json
- frontend/tsconfig.json
Overview:
1. Implement importing modules using absolute file paths
2. Fix pre-commit hooks and add pre-commit hook with lint-staged (applying ESLint and Prettier)
> fix: fix bug with absolute paths and pre-commit hooks in v1-001

- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/components/Button/Button.tsx
- frontend/src/components/TextField/TextField.tsx
- frontend/src/components/layout/Header.tsx
- frontend/src/components/layout/Menu.tsx
- frontend/src/components/layout/styled.ts
- frontend/src/constants/routes.ts
- frontend/src/pages/Layout.tsx
**Overview:**
1. Add custom component for MUI Button
2. Add custom component for MUI TextField
> [WIP] feat: add basic custom components (V1-003)

- backend/src/app.ts
- backend/src/db/connection/connectionMiddleware.ts
- backend/src/db/providers/authProvider.ts
- backend/src/db/providers/userProvider.ts
- fix returned obj from db
- fix connection func
> bug-fix: fix returned obj to plain js obj, refactor connection func

- backend/.eslintrc.json
- backend/.husky/pre-commit
- backend/package-lock.json
- backend/package.json
- backend/src/db/connection/connectionMiddleware.ts
> Feature/v1-011: add husky pre-commit

- frontend/package-lock.json
- frontend/src/components/layout/Header/Header.tsx
- frontend/src/components/layout/UserDropDown/UserDropDown.tsx
- frontend/src/components/layout/UserDropDown/UserDropDownContainer.tsx
- frontend/src/constants/menuRoles.tsx
- frontend/src/pages/Profile/index.ts
**Overview:**
1. Fixed an issue with PATHS imports
2. Fixed an issue with userName type
> bugfix/v1-021 

- frontend/src/App.tsx
- frontend/src/components/PrivateRoute/PrivateRoute.tsx
Created private routes without auth checking (todo later)
> feature/V1-013 - implement private routes

- backend/src/db/providers/clientCourseProvider.ts
Fix err 500 on client courses endpoint
> fix/V1-029 - fix error on clients courses page

- frontend/src/api/profile/getProfile.ts
- frontend/src/components/Layout/Menu/Menu.tsx
- frontend/src/components/Layout/Menu/MenuContainer.tsx
- frontend/src/constants/menuRoles.tsx
- frontend/src/types/menu.ts
**Overview:**
> 1. Implement Menu according to user role using server data (it was used statically from constants earlier)
> 2. Implement correct Menu Items displaying according to mockups and QA review ("My Profile" option in the side menu is not displayed now)
> V1-014 feat: implement menu according to the role

- frontend/src/components/PDFViewer/PDFViewer.tsx
- frontend/src/components/PDFViewer/PDFViewerContainer.tsx
- frontend/src/components/PDFViewer/styled.js
**Overview:**
> 1.  Fixed an issue with incorrect opening of the next page after clicking the "next" button (now it opens from the top of the page, not at the end)
> 2. Fixed an issue with incorrect opening of the next page after clicking the "previous" button (now it opens from the top of the page, not at the end)
> 3. Changed the design and position of navigation buttons according to mockup
> 4. Fixed an issue with additional scrollbars on the right and bottom of the screen displaying in The Firefox browser
> bugfix/V1-031:  implement correct PDFViewer working

- frontend/src/App.tsx
- frontend/src/components/NoContent/styled.ts
- frontend/src/components/PDFViewer/styled.js
- frontend/src/constants/routes.ts
- frontend/src/pages/NotFound/NotFound.tsx
- frontend/src/pages/NotFound/index.ts
- frontend/src/pages/NotFound/styled.ts
- frontend/src/pages/index.ts
**Overview:**
> 1. Added NotFound page 
> 2. Implemented redirecting the client to the common 404 page in case of trying to access unexpected page
> Feature/V1-050 Implement NotFound page

- frontend/src/components/PDFViewer/styled.js
Overview:
1. Fixed buttons position and size according to mockup
2. Fixed PDFViewer position according to new Menu Layout
> V1-031 bugfix: fixed PDF Viewer buttons position

- frontend/src/App.tsx
- frontend/src/components/AnonymousRoute/AnonymousRoute.tsx
**Overview:**
1. Implement safe route for Sign In page with redirecting already authorized client to the Profile page
> V1-055 feat: implement safe route for Sign In page

- backend/migrations/20211219190858-init_collections.js
- backend/src/db/models/ClientCourses.ts
- backend/src/db/models/User.ts
- backend/src/db/providers/clientCourseProvider.ts
- backend/src/db/providers/courseProvider.ts
- backend/src/interfaces/Ientities/IclientCourses.d.ts
- Fix clients courses response data
- Fix apply for already applied course
> fix/V1-027 - fix clients courses

- backend/src/db/providers/courseProvider.ts
- frontend/src/components/Course/styled.ts
- frontend/src/components/Layout/Header/styled.ts
- frontend/src/components/Layout/Menu/styled.ts
- frontend/src/pages/LearningCourse/styled.ts
- frontend/src/themeSettings.ts
Replaced `Lato` to `Ubuntu` font on each style component.
> [bugfix/feature/v1-064] Replaced fonts

- frontend/src/App.tsx
- frontend/src/components/Loader/Loader.tsx
- frontend/src/components/Loader/index.ts
- frontend/src/components/Loader/styled.ts
- frontend/src/pages/index.ts
**Overview:**
1. Add a common component "Loader" for using as a fallback prop of The Suspense component
2. Implement lazy loading for all App's pages except SignIn
> V1-065 feat: implement lazy loading for pages

- frontend/package-lock.json
- frontend/src/components/PDFViewer/styled.js
- frontend/src/themeSettings.ts
**Overview:**
1. If the user scrolls the document, then the whole page with the contents and page numbers was scrolled => only the main content is scrolled now
> V1-031 fix: fixed according to QA review

- frontend/src/components/Layout/Header/Header.tsx
- frontend/src/components/Layout/Header/HeaderContainer.tsx
- frontend/src/components/Layout/Header/styled.ts
Used ClickAwayListener to implement closing blocks with filters/notifications by clicking anywhere on the screen with other buttons working at the same time.
> bugfix/v1-052/topbar - closing filters & notifications

- frontend/src/components/Course/Course.tsx
- frontend/src/components/Course/styled.ts
- frontend/src/components/ProgressBar/ProgressBar.tsx
- frontend/src/components/ProgressBar/styled.ts
- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/styled.ts
- frontend/src/utils/helpers/shortify.ts
- frontend/src/utils/helpers/shortifyCourseDescription.ts
- frontend/src/utils/helpers/textLimiter.tsx
1. Fixed styles according to QA review
2. Implement correct working of shortifyCourseDescription. Now the description is shortened only if its length is longer than the maximum value
> V1-028 fix: fixed according to QA review

- frontend/src/components/Course/Course.tsx
- frontend/src/components/Course/styled.ts
- frontend/src/components/ProgressBar/styled.ts
- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/styled.ts
**Overview:**
1. Fixed styles according to QA review
2. Fixed the font style of the percentage of passing, now it doesn't change to Times New Roman, when the user moves the cursor
> V1-028 fix: fixed styles according to QA review

- frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
- frontend/src/pages/LearningCourse/FormDialog/styled.ts
Fixed styles accoding to QA review
> V1-049 fix: fixed accoding to QA review

- openApi/SUL-api-docs.yaml
>
> Implemented docs for SUL-api.  
>  
> Some changes to models will soon be required. 
>
> Docs yaml markup provided.
>
> Deployed version is [right here](https://app.swaggerhub.com/apis-docs/apolonik.danila2002/SUL-api/1.0.0)
> Feature V1-082 - Describing docs for API.

- backend/migrations/20220125143932-init_collections.js
- backend/src/db/models/Tests.ts
- backend/src/interfaces/Ientities/Itest.ts
>
> 1. Fixed QA issues (@dapodev).
> 1. Changed `tests` collection data structure (@SaXaPhonist).
> Bug-fix V1-086 - Fixed mock data related issues, changed tests mock data structure.

- frontend/src/pages/PassingTest/PassingTest.tsx
- frontend/src/pages/PassingTest/QuestionItem/styled.ts
- frontend/src/pages/PassingTest/styled.ts
**Overview:**
> 1. Fixed styles according to QA review
> V1-067 fix: fixed styles according to QA review

- openApi/SUL-api-docs.yaml
>
> QA comments related to docs updates due to implementing of `Not Found Error` fixed.
> Bug-fix v1-082 | QA comments fixed:

- frontend/src/pages/NotFound/styled.ts
**Overview**
1. Fixed an issue with content on NotFound page (font size, margins, etc.)
> fix: fixed styles of NotFound page

- frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
- frontend/src/pages/MyCourses/MyCoursesList.tsx
- frontend/src/pages/PassingTest/PassingTestContainer.tsx
- frontend/src/pages/PassingTest/TestResult/TestResult.tsx
**Overview:**
1. Fixed an issue with Result button, now it is only available on the last stage, on all the other pages only Next button is available even if the user has scrolled back
2. Fixed console errors caused by key prop
3. Replace CountDownTimer in modal window with default text (it will be changed to BE data in V1-073)
> V1-067 fix: fixed an issue with result button

- backend/src/controllers/pendingCourses/approvePendingCourse.ts
- backend/src/controllers/pendingCourses/declinePendingCourse.ts
- backend/src/controllers/tests/startTest.ts
- backend/src/db/providers/clientCourseProvider.ts
> V1-079 - fixing bugs

- frontend/src/components/Arrows/arrowBack.tsx
- frontend/src/components/Arrows/arrowForward.tsx
- frontend/src/components/Arrows/styled.ts
- frontend/src/components/PDFViewer/PDFViewer.tsx
- frontend/src/components/PDFViewer/PDFViewerContainer.tsx
- frontend/src/components/PDFViewer/styled.ts
**Overview:**
> 1. Implemented dynamical scaling of PDF pages, based on page width and parent container width.
> 2. Added responsive Help page
> V1-072 implement responsive Help page

- frontend/src/components/Layout/Header/ConfirmLogOut/ConfirmLogOut.tsx
> [bugfix-feature/v1-066] Hot style fix

- frontend/src/components/PDFViewer/styled.ts
**Overview:**
1. Fixed styles according to QA review
> V1-072 fix: fixed according to QA review

- frontend/src/pages/SignIn/styled.tsx
Fixed height according for correctly work on deploy
> [bugfix-feature/v1-068] Hot fix SignIn input height

- backend/migrations/20220125143932-init_collections.js
- backend/src/controllers/clientCourses/applyCourse.ts
- backend/src/controllers/manager/adapterManager.ts
- backend/src/controllers/manager/adapterManger.ts
- backend/src/controllers/pendingCourses/adapterSender.ts
- backend/src/controllers/pendingCourses/approvePendingCourse.ts
- backend/src/controllers/pendingCourses/declinePendingCourse.ts
- backend/src/controllers/pendingCourses/getPendingCourses.ts
- backend/src/controllers/pendingCourses/updatePendingCourse.ts
- backend/src/controllers/user/adapterUser.ts
- backend/src/interfaces/IResponse/IResponse.ts
- backend/src/interfaces/Imiddlewares/Imiddlewares.ts
- backend/src/routing/coursesRouter.ts
- backend/src/routing/employeesRouter.ts
- backend/src/routing/pendingCourses.ts
- change apply middleware
-  change migrations
- fix bugs
> Bug-fix/apply middleware

- backend/src/utils/validation/checkDuplicates.ts
- frontend/src/components/Course/styled.ts
- frontend/src/pages/CoursesList/styled.ts
Replaced some styles, hope it will work on deploy fine
> [bugfix-feature/v1-024] adapted styles for truthy work application on deploy

- frontend/src/components/Course/styled.ts
- frontend/src/pages/CoursesList/styled.ts
Updated wrongs in style on `Courses` component
> [hot-fix/mobile-width]  Updated mobile width for deploy

- frontend/src/pages/CoursesList/CoursesContainer.tsx
- frontend/src/pages/CoursesList/styled.ts
- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
- frontend/src/pages/MyCourses/MyCoursesContainer.tsx
- frontend/src/pages/MyCourses/MyCoursesList.tsx
Fixed responsive Courses List styles according to QA review
> V1-071 Bugfix responsive design for Courses List

- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
**Overview:**
> 1. Removed ProgressBar on Detailed Course page if course status is 'pending'
> 2. Added disabled state for 'Start the course' button on Detailed course page if course status is 'pending'
> bugfix V1-092 The updated design for the Details page

- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/styled.ts
**Overview:**
1. Fixed disabled button styles on Detailed course page. Now the button has the same design as the "Pending" button (if the course status is "pending")
> Bugfix/v1-092 Disabled button on Detailed course page

- frontend/src/pages/CoursesList/styled.ts
- frontend/src/pages/MyCourses/MyCoursesList.tsx
- frontend/src/pages/MyCourses/styled.ts
**Overview:** 
1. Added "Completed" button on My Courses page in case client course status is "completed"
> Bugfix V1-096 "Completed" button on the course card

- frontend/src/components/ProgressBar/styled.ts
- frontend/src/icons/checkbox.svg
- frontend/src/icons/checkboxChecked.svg
- frontend/src/pages/PassingTest/QuestionItem/styled.ts
- frontend/src/pages/PassingTest/TestResult/TestResult.tsx
- frontend/src/pages/PassingTest/TestResult/styled.ts
- frontend/src/pages/PassingTest/styled.ts
**Overview:**
1. Implemented Test page styles for mobile
2. Implemented Test page styles for tablet
3. Implemented Result page styles for mobile in case of failing/completing test
4. Implemented Result page styles for tablet in case of failing/completing test
> V1-101 Responsive design for Test & Result pages

- frontend/src/pages/LearningCourse/LearningCourse.tsx
- frontend/src/pages/LearningCourse/styled.ts
**Overview:**
1. When the user clicks on the arrows to switch the material on the Learning materials page, the click zone looks the same as on the Help page
> V1-111 Updated arrow style on the Learning materials page

- backend/migrations-backdev/20220125143932-backdev_col.js
- backend/migrations/20220125143932-init_collections.js
- backend/src/db/providers/userProvider.ts
- backend/src/interfaces/Ientities/Iusers.ts
- frontend/src/pages/Profile/Profile.tsx
- frontend/src/pages/Profile/ProfileContainer.tsx
- frontend/src/pages/Profile/UserSkills/SkillInfoContainer.tsx
- frontend/src/pages/Profile/UserSkills/UserSkills.tsx
- frontend/src/pages/Profile/UserSkills/UserSkillsContainer.tsx
- frontend/src/types/skill.ts
- frontend/src/types/user.ts
- frontend/src/utils/helpers/isSkillCompleted.ts
> 
> 1. Implemented displaying of skills according to new skills data structure.
> 1. Removed displaying of the red star when skill is totally completed.
> 1. Implemented displaying of the red star when skill group is primary for user.
> Feature/v1-095 - implement displaying primary/not tech group

- frontend/src/pages/CoursesList/styled.ts
**Overview:**
1. Fixed 'Completed' button displaying
> V1-096 Bugfix/Completed button

- frontend/src/components/Course/styled.ts
- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
- frontend/src/pages/DetailedCourse/styled.ts
- frontend/src/types/detailedCourse.ts
Overview:
1. f the user has completed the test, on the "Details" page the button "Completed" was deleted
2. The font-size of the "Back" and "Start the course" (and other name of the buttons) changed to 16px
3. If names of the buttons are "Start the course" or "Continue the test" the text is displaying in one line
4. When user clicks on "Continue the test" button on the Details page, the Learning page was displayed, now it is the testing page (the logic of the buttons is the same as on the My courses page)
> Bugfix V1-120 & V1-114

- backend/src/config/constants.ts
- backend/src/controllers/pendingCourses/approvePendingCourse.ts
- backend/src/controllers/pendingCourses/declinePendingCourse.ts
- backend/src/controllers/pendingCourses/getPendingCourses.ts
- backend/src/routing/pendingCourses.ts
- frontend/package-lock.json
- frontend/src/components/Button/DeclinedButton.tsx
- frontend/src/constants/time.ts
- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
- frontend/src/pages/DetailedCourse/DetailedCourseContainer.tsx
- frontend/src/pages/LearningCourse/FormDialog/FormDialog.tsx
- frontend/src/pages/MyCourses/MyCoursesContainer.tsx
- frontend/src/pages/MyCourses/MyCoursesList.tsx
- frontend/src/types/clientCourse.ts
- frontend/src/types/detailedCourse.ts
- frontend/src/utils/helpers/convertTestTimeout.ts
- frontend/src/utils/helpers/convertTime.ts
- fix bug with declined button
- refactor  detailed component's buttons
- add left time to declined button
> Bug-fix/109

- frontend/src/api/test/sendTestResult.ts
- frontend/src/pages/PassingTest/PassingTestContainer.tsx
- frontend/src/pages/PassingTest/TestResult/TestResult.tsx
- frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
- frontend/src/types/test.ts
> 
> - Implemented redirecting.
> - Implemented sending finishCourse request after receiving test result data automatically .
> Bugfix/v1-113 | Redirect to detailed course page after clicking on submit

- backend/src/db/providers/courseProvider.ts
- frontend/src/api/courses/getCourseMaterials.ts
- frontend/src/api/courses/index.ts
- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
- frontend/src/types/course.ts
**Overview:**
1. Implemented getCourseMaterials API request
2. Implemented correct sending(be) and receiving(fe) of materials
> V1-131 Bugfix blank Learning page

- frontend/src/App.tsx
- frontend/src/components/PrivateRoute/PrivateRoute.tsx
Fixed issue when logged user have seen blank screen after reloading page or just have been coming from main link
> bug/v1-133 | Fixed issue with the blank screen after reloading page for logged user

- frontend/src/components/Label/Label.tsx
- frontend/src/components/Label/index.ts
- frontend/src/components/Label/styled.ts
- frontend/src/components/Layout/Header/SearchCourses/SearchResultItem.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResultItemContainer.tsx
- frontend/src/components/Layout/Header/SearchCourses/styled.ts
**Overview:**
1. Added the "New" course label in the search results element (it is visible if the course has not been applied yet)
2. Implemented the Label reusable component with 'label' prop
> V1-135 Course labels of search result item

- frontend/src/pages/SkillsMap/styled.ts
- Fixed blocks location on the responsive layout
- Fixed Title size for mobile view
> Fixed responsive layout for Skills Map page

- backend/migrations-backdev/20220125143932-backdev_col.js
- backend/migrations/20220125143932-init_collections.js
>
> - Materials (video) links in migrations fixed.
> feature/v1-135 | On the Learning page, some videos are broken

- frontend/src/pages/PassingTest/QuestionItem/styled.ts
- frontend/src/pages/PassingTest/TestResult/styled.ts
- frontend/src/pages/PassingTest/styled.ts
- frontend/src/pages/Profile/UserSkills/styled.ts
**Overview:**
1. Fixed styles of Passing test and Test Result pages according to QA review
> V1-101  Bugfix: fixed Test&Result styles

- frontend/src/api/courses/getClientCourseAndMaterials.ts
- frontend/src/api/courses/index.ts
- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
>
> Implemented useGetClientCourseAndMaterials api to avoid unnecessary 500-error request.
> Bugfix/v1-131 | Fixed unnecessary (500) materials request.

- frontend/src/App.tsx
- frontend/src/components/PrivateRoute/PrivateRoute.tsx
Fixed issue when authorized user saw the blank screen after opening home page
> bug/v1-133 | Fixed issue with the blank screen for authorized user

- backend/src/controllers/manager/getEmployeeInfo.ts
- backend/src/db/providers/skillProvider.ts
- backend/src/interfaces/IResponse/IResponse.ts
- backend/src/interfaces/Ientities/Iusers.ts
- backend/src/routing/employeesRouter.ts
- backend/src/utils/normaliser/employees.ts
> 
> Added new endpoint to receive short info about employee and his courses.
>
> Postman: 
> Path: */api/employees/:id*, where `id` is user's `_id`
> Feature V1-077 | Implement getting of employee courses for manager

- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
> Bugfix/v1-131 | Fixed lost changes after unsuccessful conflict solving.

- frontend/src/pages/PassingTest/PassingTestContainer.tsx
- frontend/src/pages/PassingTest/TestResult/TestResult.tsx
- frontend/src/pages/PassingTest/TestResult/TestResultContainer.tsx
- frontend/src/types/test.ts
Added Loader if testData is fetching
> bug-fix/added loader if testData is fetching

- frontend/src/pages/PassingTest/PassingTestContainer.tsx
Added redirect from TestPage for the problem described in ticket V1-138
> bug-fix/added redirect

- frontend/src/constants/statuses.ts
- frontend/src/pages/PassingTest/PassingTestContainer.tsx
Added redirect to Course Info from Result Test
> bug-fix/v1-138 | refactor after QA testing

- frontend/src/api/myCourses/finishClientCourse.ts
- frontend/src/api/test/sendTestResult.ts
- frontend/src/components/Button/ActionButton.tsx
- frontend/src/pages/PassingTest/PassingTestContainer.tsx
- if timeout runs out test fails
> fix: timeout fails test

- frontend/src/components/Button/ButtonsEnums.ts
- frontend/src/components/Button/styled.ts
- frontend/src/pages/LearningCourse/styled.ts
1. Changed the button name from 'Start test' to 'Start the test'
2. Changed the "Next" and "Start the test" buttons size to 120x36px for mobile view
> Bug/v1 100 | Fixed buttons styles for Learning Course

- frontend/src/api/test/sendTestResult.ts
>
> Pls, don't laugh on this PR changes too much.
>
> P.s. Thanks @SaXaPhonist for his assistant.
> Feature/v1-172 | Finish course sending fixed.

- backend/package.json
- frontend/src/components/Course/Course.tsx
- frontend/src/constants/numbers.tsx
- frontend/src/pages/CoursesList/CoursesList.tsx
- frontend/src/utils/helpers/arrays/isLastElem.ts
- add additional ref for myCourses
> Bug-fix/ 148 - myCourses pagination

- frontend/src/components/Button/styled.ts
1. The font-size of the "Completed" button should be 16px (should be the same as the "Details" button)
> Bugfix/v-168 fixed Completed button styles

- backend/package.json
- backend/src/middlewares/errorHandlingMiddleware.ts
- backend/src/middlewares/loggerMiddleware.ts
- backend/src/utils/log/logger.ts
- backend/src/utils/log/loggerHelper.ts
>
> Fixed logging on the backend and added error/warning logging.
>
> - Fixed logics for logging.
> - Added logging of `CommonHttpError`s and `InternalServerError`.
> - Added new script `npm run devdebug` to display logging in dev mode.
> Feature/v1-180 | Error handling and logging updated.

- frontend/src/pages/Employees/styled.ts
Overview:
1. Fixed Employees page styles according to new design
> Bugfix/V1-074 

- frontend/src/pages/DetailedCourse/DetailedCourse.tsx
> bug-fix/ delete button on details page

- frontend/src/api/employees/getEmployeeProfile.ts
- frontend/src/components/Button/ButtonsEnums.ts
- frontend/src/pages/EmployeeProfile/EmployeeCourses/EmployeeCourses.tsx
- frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
- frontend/src/pages/EmployeeProfile/EmployeeProfileContainer.tsx
- frontend/src/pages/EmployeeProfile/styled.ts
- frontend/src/pages/Profile/UserSkills/UserSkills.tsx
- frontend/src/types/employee.ts
- frontend/src/utils/helpers/arrays/isLastElem.ts
Overview:
1. Fixed getEmployeeProfile API request (there was a bug with only Manager info displaying)
2. Removed an arrow near the Employee's name on desktop resolution
3. Added Employee's stack info
4. Fixed styles of EmployeeProfile page
5. Refactored and renamed some files, so now files and components have the same name
> V1-076 Bugfix: fixed EmployeeProfile page according to QA review

- frontend/src/components/Avatar/styled.ts
- frontend/src/pages/EmployeeProfile/AddCourseButton/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeCourses/EmployeeCourses.tsx
- frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
- frontend/src/pages/EmployeeProfile/styled.ts
- frontend/src/pages/Profile/UserSkills/UserSkills.tsx
**Fixed the following issues:**
1. The image size should be 220x220px
2. The margin-left of the image (from the left side of the "Back" button to the image) should be 122px, the margin-right of the image should be 100px, the margin-top should be 10px
3. The font-size of the name of the fields should be 18px, the font-weight should be 500, the color should be #9B9B9B
4. The font-size of the user data should be 18px
5. The distance between the stack data and the group should be 20px
6. The "Add course" button should have the font-size 16px
7. The font-size of the "Skills" and "All courses" tabs should be 16px
8. The last dividing line (which comes after the last skills) should not be displayed
> V1-076/Bugfix: fixed Employee profile page according to new design

- frontend/src/pages/LearningCourse/LearningCourse.tsx
- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
> bug-fix/184

- frontend/src/components/Button/ButtonsEnums.ts
- frontend/src/pages/LearningCourse/ActionButton/ActionButton.tsx
- frontend/src/pages/LearningCourse/LearningCourse.tsx
- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
- add  text loader while we're waiting for response
> refactor: change next button

- frontend/src/index.css
Solved the problem with changing text font-family when coursor moved out from view port
> Refactor | Refactored styles for body

- frontend/src/components/Layout/Header/SearchCourses/SearchCourses.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchCoursesContainer.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResult.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultContainer.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItem.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/SearchResultItemContainer.tsx
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/SearchResultItem/styled.ts
- frontend/src/components/Layout/Header/SearchCourses/SearchResult/types.ts
- frontend/src/components/Layout/Header/SearchCourses/types.ts
- frontend/src/components/Layout/MobileSearch/MobileSearch.tsx
- Fix problems with incorrect display of the course selected in the search
- Added closing of search results when choosing a course
- Added clearing of search field when choosing a course
> fix/V1-177 - fix searching

- backend/src/db/providers/courseProvider.ts
- Added Number conversion to query param.
> Feature/v1-191 | Bug with nPerPage fixed.

- backend/.prettierrc
- frontend/.prettierrc
- frontend/src/components/Button/ButtonVariants/styled.ts
- frontend/src/components/Image/styled.ts
- frontend/src/components/PDFViewer/PDFViewerButtons/styled.ts
- frontend/src/components/PDFViewer/PDFViewerDocument/styled.ts
- frontend/src/components/PDFViewer/styled.ts
- frontend/src/components/SnackbarProvider/styled.ts
- frontend/src/components/TextField/styled.ts
- frontend/src/pages/CoursesList/AddCourseButton/styled.ts
- frontend/src/pages/DetailedCourse/BackButton/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/EmployeeCoursesList/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/EmployeeCourses/SearchEmployeeCourse/styled.ts
- frontend/src/pages/Employees/EmployeesList/EmployeeItem/styled.ts
- frontend/src/pages/Employees/EmployeesList/styled.ts
- frontend/src/pages/PassingTest/TestResult/ResultDescription/styled.ts
- frontend/src/pages/PassingTest/TestResult/ResultProgressBar/styled.ts
- frontend/src/pages/PassingTest/TestTitleAndTimer/styled.ts
- frontend/src/pages/Profile/UserInfo/styled.ts
- frontend/src/pages/Requests/RequestItem/RequestButtons/styled.ts
- frontend/src/pages/SignIn/SignInForm/Definition/styled.tsx
- frontend/src/pages/SignIn/SignInForm/ErrorsMessenger/styled.ts
- frontend/src/pages/SignIn/SignInForm/styled.ts
- frontend/src/pages/SignIn/SignInImage/styled.ts
- frontend/src/pages/SignIn/styled.tsx
- Fixex
1. Fixed ui problems in dev
2. Changed deprecated value in eslint
> Hot bug fix | V1-190 - fixed ui problems in dev. Changed deprecated value in eslint.

- frontend/src/components/Button/ButtonVariants/ActionButton.tsx
- frontend/src/components/ConfirmLogOut/ConfirmLogOut.tsx
- frontend/src/constants/ButtonLabels.ts
- frontend/src/constants/requests.tsx
- frontend/src/pages/CoursesList/AddCourseButton/AddCourseButton.tsx
- frontend/src/pages/CoursesList/CourseActions/CourseActions.tsx
- frontend/src/pages/DetailedCourse/BackButton/BackButton.tsx
- frontend/src/pages/DetailedCourse/BackButton/styled.ts
- frontend/src/pages/DetailedCourse/DetailedCourseActions/DetailedCourseActions.tsx
- frontend/src/pages/EmployeeProfile/EmployeeProfile.tsx
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButton/ActionButton.tsx
- frontend/src/pages/LearningCourse/CourseInfoToggle/CourseInfoToggle.tsx
- frontend/src/pages/LearningCourse/LearningCourse.tsx
- frontend/src/pages/LearningCourse/styled.ts
- frontend/src/pages/PassingTest/ConfirmLeavePage/ConfirmLeavePage.tsx
- frontend/src/pages/PassingTest/TestResult/TestResult.tsx
- frontend/src/pages/PassingTest/TestResult/styled.ts
- frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
- frontend/src/pages/SignIn/SignInForm/SignInForm.tsx
**Overview:**
> 1. Replaced links over the buttons with component={Link}
> 2. Removed additional buttons with the loader
> 3. Changed logic of drawing buttons in cases of extra rendering
> Feature/v1-178 Change logic of drawing buttons

- frontend/src/api/manager/addCourseToEmployee.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/AddCourseDialogContainer.tsx
When a manager assigns courses to the user (via modal window on the emploee's profile page), these courses are displayed only after the page is refreshed
> V1-194 Bugfix: When a manager assigns courses to a user, these courses are displayed only after the page is refreshed

- frontend/src/utils/helpers/convertTime.ts
> bug-fix/wrong left time calculation

- backend/src/controllers/admin/addCourse.ts
- backend/src/controllers/admin/editCourse.ts
- backend/src/controllers/admin/preparingCourseData.ts
- backend/src/db/providers/clientCourseProvider.ts
- backend/src/db/providers/courseProvider.ts
- backend/src/db/providers/skillProvider.ts
- backend/src/db/providers/testProvider.ts
- backend/src/enums/routesEnum.ts
- backend/src/interfaces/ICourses/IQueryCourses.ts
- backend/src/routing/coursesRouter.ts
- backend/src/utils/validation/isValidComplexity.ts
- backend/src/utils/validation/isValidCourseData.ts
- backend/src/utils/validation/isValidDescription.ts
- backend/src/utils/validation/isValidText.ts
- backend/src/utils/validation/isValidTitle.ts
- frontend/src/api/myCourses/searchClientCourses.ts
Created functionality for creating course on backend side
> V1-163 Creating course endpoint

- frontend/src/components/Routes/RoleRoute.tsx
- frontend/src/components/Routes/types.ts
- frontend/src/components/Routes/types/index.ts
Fixed bug where no-founded page was displayed after reloading the page
> Bug/v1-187 | Fixed RoleRoute after reloading the page

- frontend/src/pages/EmployeeProfile/EmployeeInfo/EmployeeInfo.tsx
- frontend/src/pages/Employees/EmployeesList/EmployeeItem/EmployeeItem.tsx
- frontend/src/types/employee.ts
Fixed the bug where stack was not displayed on Employee page for Manager
> bug/v1-211 | Fixed displaying stack on Employee for Manager

- backend/src/controllers/tests/getAchievments.ts
- backend/src/db/providers/skillProvider.ts
> Bugfix: fix points for new skills

- frontend/src/api/courses/searchAllCourses.ts
- frontend/src/components/Layout/MobileSearch/MobileSearchContainer.tsx
Fixed bug where search was not worked in tablets and mobile devices
> bug/v1-213 | Fixed search for mobile

- frontend/src/components/SkillGroup/SkillGroup.tsx
- frontend/src/components/SkillGroup/SkillItem/SkillItem.tsx
- frontend/src/components/SkillGroup/SkillItem/SkillItemContainer.tsx
- frontend/src/components/SkillGroup/SkillItem/index.ts
- frontend/src/components/SkillGroup/SkillItem/styled.ts
- frontend/src/components/SkillGroup/styled.ts
- frontend/src/components/SkillGroup/types/index.ts
- frontend/src/pages/Skills/SkillsContainer.tsx
- frontend/src/pages/Skills/styled.ts
1. **Fixed**:  font-size of the "Search" should be the same as in the top bar
2. **Fixed**: The label under the name of the skill on the skill card should be removed (because its not using right now)
3. **Fixed**:  If the first letter of the skill is the same as the first letter of the category, the skill will not be displayed in the search result (if you enter only one letter), if you enter more letters, the skill will be displayed
_**Resolve method**_ - added condition to specify search, result will be displayed only after user types 2 or more symbols
4. **Fixed**: if the skill name has a long words, these words should be cut off with dots. And when the user is hovering the mouse, the full name should be displayed
Added a logic with a showing full skillName when the user hover on the …
> Feature/v1-158 | Fixed issues that founded while testing

- frontend/src/components/Avatar/styled.ts
- frontend/src/components/ProgressBar/styled.ts
- frontend/src/components/UserProfile/UserAvatar/styled.ts
- frontend/src/components/UserProfile/UserInfo/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/styled.ts
- frontend/src/pages/Profile/UserSkills/styled.ts
- Frontend
1. Refactored styles for UserProfile
2. Changed ProgressBar size for UserSkills
> Refactor | V1-207 - refactored styles for UserProfile

- frontend/src/components/Routes/RoleRoute.tsx
- Frontend
1. Fixed problems with RoleRoutes
> Bugfix | V1-234 - Fixed problems with RoleRoutes

- frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
- Frontend
1. Fixed problem with not scrolling side mobile menu
> Bugfix | V1-242 - Fixed problem with not scrolling side mobile menu

- frontend/src/pages/PendingAssessments/RequestItem/RequestButtons/RequestButtons.tsx
- frontend/src/pages/PendingAssessments/RequestItem/RequestItem.tsx
- frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
- frontend/src/pages/Requests/RequestItem/RequestItem.tsx
- frontend/src/pages/Requests/RequestItem/styled.ts
- Frontend 
1. Refactored Layout at Assesments page
2. Refactored loading logic for ActionButtons at Assesments and Pending requests pages.
> Refactor | V1-236 - Refactored Layout at Assesments page

- frontend/src/components/Layout/AuthorizedLayout/Menu/styled.ts
- frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
-Frontend 
1. Fixed scrolling NavMenu on mobiles
> Bugfix | V1-241 - Fixed scrolling NavMenu on mobiles

- backend/src/__tests__/utils/auth.test.ts
- backend/src/__tests__/utils/converters/dateTime.test.ts
- backend/src/__tests__/utils/strings.test.ts
- backend/src/__tests__/utils/typeGuards.test.ts
Filled tests base of Back-end with utils tests. (Validations tests skipped to implement in another PR)
> Improvement | Added utils tests to BE.

- backend/src/controllers/admin/editCourse/editCourse.ts
- backend/src/db/providers/courseProvider.ts
- frontend/src/api/admin/editCourseData.ts
- frontend/src/api/admin/index.ts
- frontend/src/api/courses/applyCourse.ts
- frontend/src/components/EditorTabs/ActionButtons/ActionButtons.tsx
- frontend/src/components/EditorTabs/ActionButtons/styled.ts
- frontend/src/components/EditorTabs/EditorTabsContainer.tsx
- frontend/src/components/EditorTabs/types.ts
- frontend/src/constants/courseEditor.ts
- frontend/src/constants/queryKeyConstants.ts
- frontend/src/constants/snackbarVariant.tsx
- frontend/src/pages/CourseEditor/CourseEditor.tsx
- frontend/src/pages/CourseEditor/CourseEditorContainer.tsx
- frontend/src/pages/CourseEditor/LessonsStep/LessonsStep.tsx
- frontend/src/pages/CourseEditor/LessonsStep/styled.ts
- frontend/src/pages/CourseEditor/SkillsStep/SkillsStep.tsx
- frontend/src/pages/CourseEditor/SkillsStep/styled.ts
- frontend/src/pages/CourseEditor/TestStep/TestStep.tsx
- frontend/src/pages/CourseEditor/types.ts
- frontend/src/pages/CourseEditor/utils.ts
**Overview:**
> 1. Implemented correct transition between editor steps (fixed buttons render)
> 2. Added disabled state for buttons `"Add lesson"`, `"Add skill"`,` "Add question"`,` "Submit"` in case of formik errors and loader on `Submit` in case of `isEditCourseDataMutateLoading`
> 3. Implemented API request for course updating
> 4. Implemented helper for course data formatting before submit
> 5. Implemented Course Editor form submit
> 6. Added snackbars appearing after successful/failed submit
> Feature/v1-220 Course Editor form submit

- frontend/src/components/Button/ButtonVariants/styled.ts
- frontend/src/components/Course/CourseInfo/styled.ts
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/ActionButtons.tsx
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/ActionButtonsContainer.tsx
- frontend/src/pages/EmployeeProfile/EmployeeSkillsAndCourses/AddCourseButton/AddCourseDialog/ActionButtons/styled.ts
- frontend/src/pages/EmployeeProfile/types.ts
- Frontend
1. Fixed action buttons at Apply Employee to Course dialog.
2. Fixed margin between course info and action button at Detailed Course page.
> UI Fixes | V1-253 - Fixed UI

- frontend/src/components/Layout/AuthorizedLayout/MobileMenu/styled.ts
- Frontend
1. Fixed mobile side menu.
> Bugfix | V1-241 Fixed mobile menu after conversation

- frontend/src/api/manager/approveRequest.ts
- frontend/src/pages/Requests/RequestItem/RequestButtons/RequestButtons.tsx
- frontend/src/pages/Requests/RequestItem/RequestItem.tsx
- frontend/src/pages/Requests/Requests.tsx
- frontend/src/pages/Requests/RequestsContainer.tsx
- frontend/src/pages/Requests/types.ts
- frontend/src/types/api.dto.ts
- Frontend
1. Fixed Action Buttons at Pending Request page
- Task link: https://trello.com/c/LBz0fRfd/270-v1-263-on-the-pending-requests-and-assessments-pages-when-the-user-clicks-on-the-accept-button-the-reject-button-also-has-the-lo
> Fix | V1-263 - Fixed Action Buttons at Pending Request page

- frontend/src/pages/LearningCourse/LearningCourse.tsx
- frontend/src/pages/LearningCourse/Material/Material.tsx
- frontend/src/pages/LearningCourse/Material/styled.ts
- frontend/src/pages/LearningCourse/StageController/styled.ts
- Frontend
1. Added some UI fixes for LearningCourse page
> UI fixes at LearningCourse page

- frontend/src/api/courses/getClientCourse.ts
- frontend/src/api/courses/getCourseMaterials.ts
- frontend/src/api/courses/index.ts
- frontend/src/pages/CourseCreator/CourseCreatorContainer.tsx
- frontend/src/pages/LearningCourse/LearningCourseContainer.tsx
Fixed api GetClientCourse & GetCourseMaterials
Fixed LaarnigCourseContainer according to the clientCourse and  courseMaterials data, renamed constants, fixed misspaling
> bug/v1-261 | Fixed duplicate requests for Learning Course page

- frontend/src/components/Layout/AuthorizedLayout/Header/SearchCourses/SearchCoursesContainer.tsx
- frontend/src/components/NotificationsBar/NotificationsBarContainer.tsx
- Frontend
1. Fixed bug with outclick for notifications and search
point 1 from this ticket: https://trello.com/c/rlxJ6Jn6/279-v1-271-issues-with-notifications-and-courses
> Bugfix | V1-271 Fixed notifications and search in header

- frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploader.tsx
- frontend/src/pages/CourseEditor/components/ImagesUploader/ImagesUploaderContainer.tsx
- Frontend
1. Fixed error messages for uploader at Course Creator/Editor
> Fixed error messages for uploader at Course Creator/Editor
